-- Kanji Memory Game — schema inicial
-- Rode no Supabase: SQL Editor > New query > cole e execute.

create table if not exists public.kanji (
  id            text primary key,           -- K001...
  kanji         text not null,
  significado   text not null,
  mundo         text,
  fase          int,
  hiragana      text,
  romaji        text,
  onyomi        text[] default '{}',
  kunyomi       text[] default '{}',
  tracos        int,
  needs_review  boolean default true,
  status        text default 'Novo',
  atualizado_em timestamptz default now()
);

create index if not exists kanji_fase_idx on public.kanji (fase);

-- RLS: qualquer um pode LER; escrita só pelo service_role (server).
alter table public.kanji enable row level security;

drop policy if exists "leitura publica do catalogo" on public.kanji;
create policy "leitura publica do catalogo"
  on public.kanji for select
  using (true);

-- Sem policy de insert/update/delete para anon/authenticated:
-- gravações acontecem apenas via service_role (que ignora RLS), pelo backend.

-- Atualiza atualizado_em em cada update
create or replace function public.touch_kanji() returns trigger as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_touch_kanji on public.kanji;
create trigger trg_touch_kanji before update on public.kanji
  for each row execute function public.touch_kanji();

-- Seed gerado por scripts/gerar_seed_sql.py
insert into public.kanji
  (id, kanji, significado, mundo, fase, hiragana, romaji, onyomi, kunyomi, tracos, needs_review, status)
values
  ('K001', '一', 'Um', 'Primeiros Símbolos', 1, 'いち', 'ICHI', '{"イチ","イツ"}', '{"ひと","ひとつ"}', 1, false, 'Validado para protótipo'),
  ('K002', '二', 'Dois', 'Primeiros Símbolos', 1, 'に', 'NI', '{"ニ"}', '{"ふた","ふたつ"}', 2, false, 'Validado para protótipo'),
  ('K003', '三', 'Três', 'Primeiros Símbolos', 1, 'さん', 'SAN', '{"サン"}', '{"み","みっつ"}', 3, false, 'Validado para protótipo'),
  ('K004', '四', 'Quatro', 'Primeiros Símbolos', 1, 'よん', 'YON', '{"シ"}', '{"よ","よん","よっつ"}', 5, false, 'Validado para protótipo'),
  ('K005', '五', 'Cinco', 'Primeiros Símbolos', 1, 'ご', 'GO', '{"ゴ"}', '{"いつ","いつつ"}', 4, false, 'Validado para protótipo'),
  ('K006', '六', 'Seis', 'Primeiros Símbolos', 1, 'ろく', 'ROKU', '{"ロク"}', '{"む","むっつ"}', 4, false, 'Validado para protótipo'),
  ('K007', '七', 'Sete', 'Primeiros Símbolos', 1, 'なな', 'NANA', '{"シチ"}', '{"なな","ななつ"}', 2, false, 'Validado para protótipo'),
  ('K008', '八', 'Oito', 'Primeiros Símbolos', 1, 'はち', 'HACHI', '{"ハチ"}', '{"や","やっつ"}', 2, false, 'Validado para protótipo'),
  ('K009', '九', 'Nove', 'Primeiros Símbolos', 1, 'きゅう', 'KYUU', '{"キュウ","ク"}', '{"ここの","ここのつ"}', 2, false, 'Validado para protótipo'),
  ('K010', '十', 'Dez', 'Primeiros Símbolos', 1, 'じゅう', 'JUU', '{"ジュウ","ジッ"}', '{"とお"}', 2, false, 'Validado para protótipo'),
  ('K011', '右', 'Direita', 'Primeiros Símbolos', 2, 'みぎ', 'MIGI', '{"ウ","ユウ"}', '{"みぎ"}', 5, true, 'Revisar leitura (auto)'),
  ('K012', '雨', 'Chuva', 'Primeiros Símbolos', 2, 'あめ', 'AME', '{"ウ"}', '{"-さめ","あま-","あめ"}', 8, true, 'Revisar leitura (auto)'),
  ('K013', '円', 'Círculo; iene', 'Primeiros Símbolos', 2, 'まど', 'MADO', '{"エン"}', '{"まど","まど.か","まる","まる.い","まろ.やか"}', 4, true, 'Revisar leitura (auto)'),
  ('K014', '王', 'Rei', 'Primeiros Símbolos', 2, 'おう', 'OU', '{"-ノウ","オウ"}', '{}', 4, true, 'Revisar leitura (auto)'),
  ('K015', '音', 'Som', 'Primeiros Símbolos', 2, 'おと', 'OTO', '{"-ノン","イン","オン"}', '{"おと","ね"}', 9, true, 'Revisar leitura (auto)'),
  ('K016', '下', 'Abaixo; descer', 'Primeiros Símbolos', 2, 'お', 'O', '{"カ","ゲ"}', '{"-くだ.す","お.りる","お.ろす","くだ.さる","くだ.す","くだ.り","くだ.る","さ.がる","さ.げる","した","しも","もと"}', 3, true, 'Revisar leitura (auto)'),
  ('K017', '火', 'Fogo', 'Primeiros Símbolos', 2, 'ひ', 'HI', '{"カ"}', '{"-び","ひ","ほ-"}', 4, true, 'Revisar leitura (auto)'),
  ('K018', '花', 'Flor', 'Primeiros Símbolos', 2, 'はな', 'HANA', '{"カ","ケ"}', '{"はな"}', 7, true, 'Revisar leitura (auto)'),
  ('K019', '貝', 'Concha', 'Primeiros Símbolos', 2, 'かい', 'KAI', '{"バイ"}', '{"かい"}', 7, true, 'Revisar leitura (auto)'),
  ('K020', '学', 'Estudo; aprender', 'Primeiros Símbolos', 2, 'まな', 'MANA', '{"ガク"}', '{"まな.ぶ"}', 8, true, 'Revisar leitura (auto)'),
  ('K021', '気', 'Energia; espírito', 'Primeiros Símbolos', 3, 'き', 'KI', '{"キ","ケ"}', '{"き"}', 6, true, 'Revisar leitura (auto)'),
  ('K022', '休', 'Descansar', 'Primeiros Símbolos', 3, 'やす', 'YASU', '{"キュウ"}', '{"やす.まる","やす.む","やす.める"}', 6, true, 'Revisar leitura (auto)'),
  ('K023', '玉', 'Joia; esfera', 'Primeiros Símbolos', 3, 'たま', 'TAMA', '{"ギョク"}', '{"-だま","たま","たま-"}', 5, true, 'Revisar leitura (auto)'),
  ('K024', '金', 'Ouro; dinheiro', 'Primeiros Símbolos', 3, 'かね', 'KANE', '{"キン","コン","ゴン"}', '{"-がね","かな-","かね"}', 8, true, 'Revisar leitura (auto)'),
  ('K025', '空', 'Céu; vazio', 'Primeiros Símbolos', 3, 'あ', 'A', '{"クウ"}', '{"あ.き","あ.く","あ.ける","から","す.かす","す.く","そら","むな.しい"}', 8, true, 'Revisar leitura (auto)'),
  ('K026', '月', 'Lua; mês', 'Primeiros Símbolos', 3, 'つき', 'TSUKI', '{"ガツ","ゲツ"}', '{"つき"}', 4, true, 'Revisar leitura (auto)'),
  ('K027', '犬', 'Cão', 'Primeiros Símbolos', 3, 'いぬ', 'INU', '{"ケン"}', '{"いぬ","いぬ-"}', 4, true, 'Revisar leitura (auto)'),
  ('K028', '見', 'Ver', 'Primeiros Símbolos', 3, 'み', 'MI', '{"ケン"}', '{"み.える","み.せる","み.る"}', 7, true, 'Revisar leitura (auto)'),
  ('K029', '口', 'Boca', 'Primeiros Símbolos', 3, 'くち', 'KUCHI', '{"ク","コウ"}', '{"くち"}', 3, true, 'Revisar leitura (auto)'),
  ('K030', '校', 'Escola', 'Primeiros Símbolos', 3, 'きょう', 'KYOU', '{"キョウ","コウ"}', '{}', 10, true, 'Revisar leitura (auto)'),
  ('K031', '左', 'Esquerda', 'Primeiros Símbolos', 4, 'ひだり', 'HIDARI', '{"サ","シャ"}', '{"ひだり"}', 5, true, 'Revisar leitura (auto)'),
  ('K032', '山', 'Montanha', 'Primeiros Símbolos', 4, 'やま', 'YAMA', '{"サン","セン"}', '{"やま"}', 3, true, 'Revisar leitura (auto)'),
  ('K033', '子', 'Criança', 'Primeiros Símbolos', 4, 'こ', 'KO', '{"シ","ス","ツ"}', '{"-こ","こ","ね"}', 3, true, 'Revisar leitura (auto)'),
  ('K034', '糸', 'Fio', 'Primeiros Símbolos', 4, 'いと', 'ITO', '{"シ"}', '{"いと"}', 6, true, 'Revisar leitura (auto)'),
  ('K035', '字', 'Caractere; letra', 'Primeiros Símbolos', 4, 'あざ', 'AZA', '{"ジ"}', '{"-な","あざ","あざな"}', 6, true, 'Revisar leitura (auto)'),
  ('K036', '耳', 'Orelha', 'Primeiros Símbolos', 4, 'みみ', 'MIMI', '{"ジ"}', '{"みみ"}', 6, true, 'Revisar leitura (auto)'),
  ('K037', '車', 'Carro; veículo', 'Primeiros Símbolos', 4, 'くるま', 'KURUMA', '{"シャ"}', '{"くるま"}', 7, true, 'Revisar leitura (auto)'),
  ('K038', '手', 'Mão', 'Primeiros Símbolos', 4, 'て', 'TE', '{"シュ","ズ"}', '{"-て","た-","て","て-"}', 4, true, 'Revisar leitura (auto)'),
  ('K039', '出', 'Sair', 'Primeiros Símbolos', 4, 'い', 'I', '{"シュツ","スイ"}', '{"-だ.す","-で","い.だす","い.でる","だ.す","で.る"}', 5, true, 'Revisar leitura (auto)'),
  ('K040', '女', 'Mulher', 'Primeiros Símbolos', 4, 'おんな', 'ONNA', '{"ジョ","ニョ","ニョウ"}', '{"おんな","め"}', 3, true, 'Revisar leitura (auto)'),
  ('K041', '小', 'Pequeno', 'Primeiros Símbolos', 5, 'ちい', 'CHII', '{"ショウ"}', '{"お-","こ-","さ-","ちい.さい"}', 3, true, 'Revisar leitura (auto)'),
  ('K042', '上', 'Acima; subir', 'Primeiros Símbolos', 5, 'あ', 'A', '{"シャン","ショウ","ジョウ"}', '{"-あ.がり","-あ.がる","-あ.げる","-うえ","あ.がり","あ.がる","あ.げる","うえ","うわ-","かみ","たてまつ.る","のぼ.す","のぼ.せる","のぼ.り","のぼ.る"}', 3, true, 'Revisar leitura (auto)'),
  ('K043', '森', 'Floresta', 'Primeiros Símbolos', 5, 'もり', 'MORI', '{"シン"}', '{"もり"}', 12, true, 'Revisar leitura (auto)'),
  ('K044', '人', 'Pessoa', 'Primeiros Símbolos', 5, 'ひと', 'HITO', '{"ジン","ニン"}', '{"-と","-り","ひと"}', 2, true, 'Revisar leitura (auto)'),
  ('K045', '水', 'Água', 'Primeiros Símbolos', 5, 'みず', 'MIZU', '{"スイ"}', '{"みず","みず-"}', 4, true, 'Revisar leitura (auto)'),
  ('K046', '正', 'Correto', 'Primeiros Símbolos', 5, 'ただ', 'TADA', '{"ショウ","セイ"}', '{"ただ.しい","ただ.す","まさ","まさ.に"}', 5, true, 'Revisar leitura (auto)'),
  ('K047', '生', 'Vida; nascer', 'Primeiros Símbolos', 5, 'い', 'I', '{"ショウ","セイ"}', '{"-う","い.かす","い.きる","い.ける","う.まれ","う.まれる","う.む","うま.れる","うまれ","お.う","き","な.す","な.る","なま","なま-","は.える","は.やす","む.す"}', 5, true, 'Revisar leitura (auto)'),
  ('K048', '青', 'Azul; verde', 'Primeiros Símbolos', 5, 'あお', 'AO', '{"ショウ","セイ"}', '{"あお","あお-","あお.い"}', 8, true, 'Revisar leitura (auto)'),
  ('K049', '石', 'Pedra', 'Primeiros Símbolos', 5, 'いし', 'ISHI', '{"コク","シャク","セキ"}', '{"いし"}', 5, true, 'Revisar leitura (auto)'),
  ('K050', '赤', 'Vermelho', 'Primeiros Símbolos', 5, 'あか', 'AKA', '{"シャク","セキ"}', '{"あか","あか-","あか.い","あか.らむ","あか.らめる"}', 7, true, 'Revisar leitura (auto)'),
  ('K051', '先', 'Antes; à frente', 'Natureza', 6, 'さき', 'SAKI', '{"セン"}', '{"さき","ま.ず"}', 6, true, 'Revisar leitura (auto)'),
  ('K052', '千', 'Mil', 'Natureza', 6, 'ち', 'CHI', '{"セン"}', '{"ち"}', 3, true, 'Revisar leitura (auto)'),
  ('K053', '川', 'Rio', 'Natureza', 6, 'かわ', 'KAWA', '{"セン"}', '{"かわ"}', 3, true, 'Revisar leitura (auto)'),
  ('K054', '早', 'Cedo; rápido', 'Natureza', 6, 'はや', 'HAYA', '{"サッ","ソウ"}', '{"さ-","はや","はや-","はや.い","はや.まる","はや.める"}', 6, true, 'Revisar leitura (auto)'),
  ('K055', '草', 'Grama', 'Natureza', 6, 'くさ', 'KUSA', '{"ソウ"}', '{"-ぐさ","くさ","くさ-"}', 9, true, 'Revisar leitura (auto)'),
  ('K056', '足', 'Pé; perna', 'Natureza', 6, 'あし', 'ASHI', '{"ソク"}', '{"あし","た.す","た.りる","た.る"}', 7, true, 'Revisar leitura (auto)'),
  ('K057', '村', 'Vila', 'Natureza', 6, 'むら', 'MURA', '{"ソン"}', '{"むら"}', 7, true, 'Revisar leitura (auto)'),
  ('K058', '大', 'Grande', 'Natureza', 6, 'おお', 'OO', '{"タイ","ダイ"}', '{"-おお.いに","おお-","おお.きい"}', 3, true, 'Revisar leitura (auto)'),
  ('K059', '男', 'Homem', 'Natureza', 6, 'お', 'O', '{"ダン","ナン"}', '{"お","おとこ"}', 7, true, 'Revisar leitura (auto)'),
  ('K060', '竹', 'Bambu', 'Natureza', 6, 'たけ', 'TAKE', '{"チク"}', '{"たけ"}', 6, true, 'Revisar leitura (auto)'),
  ('K061', '中', 'Centro; dentro', 'Natureza', 7, 'あた', 'ATA', '{"チュウ"}', '{"あた.る","うち","なか"}', 4, true, 'Revisar leitura (auto)'),
  ('K062', '虫', 'Inseto', 'Natureza', 7, 'むし', 'MUSHI', '{"キ","チュウ"}', '{"むし"}', 6, true, 'Revisar leitura (auto)'),
  ('K063', '町', 'Cidade pequena', 'Natureza', 7, 'まち', 'MACHI', '{"チョウ"}', '{"まち"}', 7, true, 'Revisar leitura (auto)'),
  ('K064', '天', 'Céu', 'Natureza', 7, 'あまつ', 'AMATSU', '{"テン"}', '{"あま-","あまつ","あめ"}', 4, true, 'Revisar leitura (auto)'),
  ('K065', '田', 'Arrozal', 'Natureza', 7, 'た', 'TA', '{"デン"}', '{"た"}', 5, true, 'Revisar leitura (auto)'),
  ('K066', '土', 'Terra; solo', 'Natureza', 7, 'つち', 'TSUCHI', '{"ト","ド"}', '{"つち"}', 3, true, 'Revisar leitura (auto)'),
  ('K067', '日', 'Sol; dia', 'Natureza', 7, 'ひ', 'HI', '{"ジツ","ニチ"}', '{"-か","-び","ひ"}', 4, true, 'Revisar leitura (auto)'),
  ('K068', '入', 'Entrar', 'Natureza', 7, 'い', 'I', '{"ジュ","ニュウ"}', '{"-い.り","-い.る","-い.れ","い.る","い.れる","はい.る"}', 2, true, 'Revisar leitura (auto)'),
  ('K069', '年', 'Ano', 'Natureza', 7, 'とし', 'TOSHI', '{"ネン"}', '{"とし"}', 6, true, 'Revisar leitura (auto)'),
  ('K070', '白', 'Branco', 'Natureza', 7, 'しろ', 'SHIRO', '{"ハク","ビャク"}', '{"しら-","しろ","しろ.い"}', 5, true, 'Revisar leitura (auto)'),
  ('K071', '百', 'Cem', 'Natureza', 8, 'もも', 'MOMO', '{"ヒャク","ビャク"}', '{"もも"}', 6, true, 'Revisar leitura (auto)'),
  ('K072', '文', 'Texto; literatura', 'Natureza', 8, 'あや', 'AYA', '{"ブン","モン"}', '{"あや","ふみ"}', 4, true, 'Revisar leitura (auto)'),
  ('K073', '本', 'Livro; origem', 'Natureza', 8, 'もと', 'MOTO', '{"ホン"}', '{"もと"}', 5, true, 'Revisar leitura (auto)'),
  ('K074', '名', 'Nome', 'Natureza', 8, 'な', 'NA', '{"ミョウ","メイ"}', '{"-な","な"}', 6, true, 'Revisar leitura (auto)'),
  ('K075', '木', 'Árvore; madeira', 'Natureza', 8, 'き', 'KI', '{"ボク","モク"}', '{"き","こ-"}', 4, true, 'Revisar leitura (auto)'),
  ('K076', '目', 'Olho', 'Natureza', 8, 'め', 'ME', '{"ボク","モク"}', '{"-め","ま-","め"}', 5, true, 'Revisar leitura (auto)'),
  ('K077', '夕', 'Entardecer', 'Natureza', 8, 'ゆう', 'YUU', '{"セキ"}', '{"ゆう"}', 3, true, 'Revisar leitura (auto)'),
  ('K078', '立', 'Ficar em pé', 'Natureza', 8, 'た', 'TA', '{"リットル","リツ","リュウ"}', '{"-た.つ","-た.て","-た.てる","-だ.て","-だ.てる","た.ち-","た.つ","た.て-","た.てる","たて-"}', 5, true, 'Revisar leitura (auto)'),
  ('K079', '力', 'Força', 'Natureza', 8, 'ちから', 'CHIKARA', '{"リイ","リキ","リョク"}', '{"ちから"}', 2, true, 'Revisar leitura (auto)'),
  ('K080', '林', 'Bosque', 'Natureza', 8, 'はやし', 'HAYASHI', '{"リン"}', '{"はやし"}', 8, true, 'Revisar leitura (auto)'),
  ('K081', '引', 'Puxar', 'Natureza', 9, 'ひ', 'HI', '{"イン"}', '{"ひ.く","ひ.ける"}', 4, true, 'Revisar leitura (auto)'),
  ('K082', '羽', 'Pena; asa', 'Natureza', 9, 'は', 'HA', '{"ウ"}', '{"は","はね","わ"}', 6, true, 'Revisar leitura (auto)'),
  ('K083', '雲', 'Nuvem', 'Natureza', 9, 'くも', 'KUMO', '{"ウン"}', '{"-ぐも","くも"}', 12, true, 'Revisar leitura (auto)'),
  ('K084', '園', 'Jardim; parque', 'Natureza', 9, 'その', 'SONO', '{"エン"}', '{"その"}', 13, true, 'Revisar leitura (auto)'),
  ('K085', '遠', 'Distante', 'Natureza', 9, 'とお', 'TOO', '{"エン","オン"}', '{"とお.い"}', 13, true, 'Revisar leitura (auto)'),
  ('K086', '黄', 'Amarelo', 'Natureza', 9, 'き', 'KI', '{"オウ","コウ"}', '{"き","こ-"}', 11, true, 'Revisar leitura (auto)'),
  ('K087', '何', 'O quê', 'Natureza', 9, 'なに', 'NANI', '{"カ"}', '{"なに","なに-","なん","なん-"}', 7, true, 'Revisar leitura (auto)'),
  ('K088', '夏', 'Verão', 'Natureza', 9, 'なつ', 'NATSU', '{"カ","ガ","ゲ"}', '{"なつ"}', 10, true, 'Revisar leitura (auto)'),
  ('K089', '家', 'Casa; família', 'Natureza', 9, 'いえ', 'IE', '{"カ","ケ"}', '{"いえ","うち","や"}', 10, true, 'Revisar leitura (auto)'),
  ('K090', '科', 'Matéria; departamento', 'Natureza', 9, 'か', 'KA', '{"カ"}', '{}', 9, true, 'Revisar leitura (auto)'),
  ('K091', '歌', 'Canção; cantar', 'Natureza', 10, 'うた', 'UTA', '{"カ"}', '{"うた","うた.う"}', 14, true, 'Revisar leitura (auto)'),
  ('K092', '画', 'Imagem; traço', 'Natureza', 10, 'えが', 'EGA', '{"エ","カイ","カク","ガ"}', '{"えが.く","かぎ.る","かく.する","はか.る","はかりごと"}', 8, true, 'Revisar leitura (auto)'),
  ('K093', '会', 'Encontrar; reunião', 'Natureza', 10, 'あ', 'A', '{"エ","カイ"}', '{"あ.う","あ.わせる","あつ.まる"}', 6, true, 'Revisar leitura (auto)'),
  ('K094', '回', 'Vez; girar', 'Natureza', 10, 'か', 'KA', '{"エ","カイ"}', '{"-まわ.し","-まわ.す","-まわ.り","-まわ.る","か.える","まわ.し-","まわ.す","まわ.る","もとお.る"}', 6, true, 'Revisar leitura (auto)'),
  ('K095', '海', 'Mar', 'Natureza', 10, 'うみ', 'UMI', '{"カイ"}', '{"うみ"}', 9, true, 'Revisar leitura (auto)'),
  ('K096', '絵', 'Desenho; pintura', 'Natureza', 10, 'え', 'E', '{"エ","カイ"}', '{}', 12, true, 'Revisar leitura (auto)'),
  ('K097', '外', 'Fora', 'Natureza', 10, 'そと', 'SOTO', '{"ガイ","ゲ"}', '{"そと","と-","はず.す","はず.れる","ほか"}', 5, true, 'Revisar leitura (auto)'),
  ('K098', '角', 'Ângulo; canto', 'Natureza', 10, 'かど', 'KADO', '{"カク"}', '{"かど","つの"}', 7, true, 'Revisar leitura (auto)'),
  ('K099', '楽', 'Diversão; música', 'Natureza', 10, 'この', 'KONO', '{"ガク","ゴウ","ラク"}', '{"この.む","たの.しい","たの.しむ"}', 13, true, 'Revisar leitura (auto)'),
  ('K100', '活', 'Vida; atividade', 'Natureza', 10, 'い', 'I', '{"カツ"}', '{"い.かす","い.きる","い.ける"}', 9, true, 'Revisar leitura (auto)'),
  ('K101', '間', 'Intervalo; espaço', 'Vida Cotidiana', 11, 'あい', 'AI', '{"カン","ケン"}', '{"あい","あいだ","ま"}', 12, true, 'Revisar leitura (auto)'),
  ('K102', '丸', 'Redondo', 'Vida Cotidiana', 11, 'まる', 'MARU', '{"ガン"}', '{"まる","まる.い","まる.める"}', 3, true, 'Revisar leitura (auto)'),
  ('K103', '岩', 'Rocha', 'Vida Cotidiana', 11, 'いわ', 'IWA', '{"ガン"}', '{"いわ"}', 8, true, 'Revisar leitura (auto)'),
  ('K104', '顔', 'Rosto', 'Vida Cotidiana', 11, 'かお', 'KAO', '{"ガン"}', '{"かお"}', 18, true, 'Revisar leitura (auto)'),
  ('K105', '帰', 'Voltar', 'Vida Cotidiana', 11, 'おく', 'OKU', '{"キ"}', '{"おく.る","かえ.す","かえ.る","とつ.ぐ"}', 10, true, 'Revisar leitura (auto)'),
  ('K106', '汽', 'Vapor', 'Vida Cotidiana', 11, 'き', 'KI', '{"キ"}', '{}', 7, true, 'Revisar leitura (auto)'),
  ('K107', '記', 'Registrar', 'Vida Cotidiana', 11, 'しる', 'SHIRU', '{"キ"}', '{"しる.す"}', 10, true, 'Revisar leitura (auto)'),
  ('K108', '弓', 'Arco', 'Vida Cotidiana', 11, 'ゆみ', 'YUMI', '{"キュウ"}', '{"ゆみ"}', 3, true, 'Revisar leitura (auto)'),
  ('K109', '牛', 'Vaca; boi', 'Vida Cotidiana', 11, 'うし', 'USHI', '{"ギュウ"}', '{"うし"}', 4, true, 'Revisar leitura (auto)'),
  ('K110', '魚', 'Peixe', 'Vida Cotidiana', 11, 'うお', 'UO', '{"ギョ"}', '{"-ざかな","うお","さかな"}', 11, true, 'Revisar leitura (auto)'),
  ('K111', '京', 'Capital', 'Vida Cotidiana', 12, 'みやこ', 'MIYAKO', '{"キョウ","キン","ケイ"}', '{"みやこ"}', 8, true, 'Revisar leitura (auto)'),
  ('K112', '強', 'Forte', 'Vida Cotidiana', 12, 'こわ', 'KOWA', '{"キョウ","ゴウ"}', '{"こわ.い","し.いる","つよ.い","つよ.まる","つよ.める"}', 11, true, 'Revisar leitura (auto)'),
  ('K113', '教', 'Ensinar', 'Vida Cotidiana', 12, 'おし', 'OSHI', '{"キョウ"}', '{"おし.える","おそ.わる"}', 11, true, 'Revisar leitura (auto)'),
  ('K114', '近', 'Perto', 'Vida Cotidiana', 12, 'ちか', 'CHIKA', '{"キン","コン"}', '{"ちか.い"}', 7, true, 'Revisar leitura (auto)'),
  ('K115', '兄', 'Irmão mais velho', 'Vida Cotidiana', 12, 'あに', 'ANI', '{"キョウ","ケイ"}', '{"あに"}', 5, true, 'Revisar leitura (auto)'),
  ('K116', '形', 'Forma', 'Vida Cotidiana', 12, 'かた', 'KATA', '{"ギョウ","ケイ"}', '{"-がた","かた","かたち","なり"}', 7, true, 'Revisar leitura (auto)'),
  ('K117', '計', 'Medir; plano', 'Vida Cotidiana', 12, 'はか', 'HAKA', '{"ケイ"}', '{"はか.らう","はか.る"}', 9, true, 'Revisar leitura (auto)'),
  ('K118', '元', 'Origem; início', 'Vida Cotidiana', 12, 'もと', 'MOTO', '{"ガン","ゲン"}', '{"もと"}', 4, true, 'Revisar leitura (auto)'),
  ('K119', '原', 'Origem; campo', 'Vida Cotidiana', 12, 'はら', 'HARA', '{"ゲン"}', '{"はら"}', 10, true, 'Revisar leitura (auto)'),
  ('K120', '言', 'Dizer; palavra', 'Vida Cotidiana', 12, 'い', 'I', '{"ゲン","ゴン"}', '{"い.う","こと"}', 7, true, 'Revisar leitura (auto)'),
  ('K121', '古', 'Antigo', 'Vida Cotidiana', 13, 'ふる', 'FURU', '{"コ"}', '{"-ふる.す","ふる-","ふる.い"}', 5, true, 'Revisar leitura (auto)'),
  ('K122', '戸', 'Porta; residência', 'Vida Cotidiana', 13, 'と', 'TO', '{"コ"}', '{"と"}', 4, true, 'Revisar leitura (auto)'),
  ('K123', '午', 'Meio-dia', 'Vida Cotidiana', 13, 'うま', 'UMA', '{"ゴ"}', '{"うま"}', 4, true, 'Revisar leitura (auto)'),
  ('K124', '後', 'Depois; atrás', 'Vida Cotidiana', 13, 'あと', 'ATO', '{"コウ","ゴ"}', '{"あと","うし.ろ","うしろ","おく.れる","のち"}', 9, true, 'Revisar leitura (auto)'),
  ('K125', '語', 'Língua; palavra', 'Vida Cotidiana', 13, 'かた', 'KATA', '{"ゴ"}', '{"かた.らう","かた.る"}', 14, true, 'Revisar leitura (auto)'),
  ('K126', '交', 'Cruzar; conviver', 'Vida Cotidiana', 13, 'か', 'KA', '{"コウ"}', '{"-か.う","か.わす","かわ.す","こもごも","ま.ざる","ま.じる","ま.ぜる","まじ.える","まじ.る","まじ.わる"}', 6, true, 'Revisar leitura (auto)'),
  ('K127', '光', 'Luz', 'Vida Cotidiana', 13, 'ひか', 'HIKA', '{"コウ"}', '{"ひか.る","ひかり"}', 6, true, 'Revisar leitura (auto)'),
  ('K128', '公', 'Público', 'Vida Cotidiana', 13, 'おおやけ', 'OOYAKE', '{"ク","コウ"}', '{"おおやけ"}', 4, true, 'Revisar leitura (auto)'),
  ('K129', '工', 'Construção; ofício', 'Vida Cotidiana', 13, 'く', 'KU', '{"ク","グ","コウ"}', '{}', 3, true, 'Revisar leitura (auto)'),
  ('K130', '広', 'Amplo', 'Vida Cotidiana', 13, 'ひろ', 'HIRO', '{"コウ"}', '{"ひろ.い","ひろ.がる","ひろ.げる","ひろ.まる","ひろ.める"}', 5, true, 'Revisar leitura (auto)'),
  ('K131', '考', 'Pensar', 'Vida Cotidiana', 14, 'かんが', 'KANGA', '{"コウ"}', '{"かんが.え","かんが.える"}', 6, true, 'Revisar leitura (auto)'),
  ('K132', '行', 'Ir; realizar', 'Vida Cotidiana', 14, 'い', 'I', '{"アン","ギョウ","コウ"}', '{"-い.き","-いき","-ゆ.き","-ゆき","い.く","おこ.なう","おこな.う","ゆ.く"}', 6, true, 'Revisar leitura (auto)'),
  ('K133', '高', 'Alto; caro', 'Vida Cotidiana', 14, 'たか', 'TAKA', '{"コウ"}', '{"-だか","たか","たか.い","たか.まる","たか.める"}', 10, true, 'Revisar leitura (auto)'),
  ('K134', '合', 'Unir; combinar', 'Vida Cotidiana', 14, 'あ', 'A', '{"カッ","ガッ","ゴウ"}', '{"-あ.い","-あ.う","-あ.わせる","-あい","あ.い","あ.う","あ.わす","あ.わせる","あい-"}', 6, true, 'Revisar leitura (auto)'),
  ('K135', '国', 'País', 'Vida Cotidiana', 14, 'くに', 'KUNI', '{"コク"}', '{"くに"}', 8, true, 'Revisar leitura (auto)'),
  ('K136', '黒', 'Preto', 'Vida Cotidiana', 14, 'くろ', 'KURO', '{"コク"}', '{"くろ","くろ.い","くろ.ずむ"}', 11, true, 'Revisar leitura (auto)'),
  ('K137', '今', 'Agora', 'Vida Cotidiana', 14, 'いま', 'IMA', '{"キン","コン"}', '{"いま"}', 4, true, 'Revisar leitura (auto)'),
  ('K138', '才', 'Talento; anos de idade', 'Vida Cotidiana', 14, 'さい', 'SAI', '{"サイ"}', '{}', 3, true, 'Revisar leitura (auto)'),
  ('K139', '細', 'Fino; detalhado', 'Vida Cotidiana', 14, 'こま', 'KOMA', '{"サイ"}', '{"こま.か","こま.かい","ほそ.い","ほそ.る"}', 11, true, 'Revisar leitura (auto)'),
  ('K140', '作', 'Fazer; criar', 'Vida Cotidiana', 14, 'つく', 'TSUKU', '{"サ","サク"}', '{"-づく.り","つく.り","つく.る"}', 7, true, 'Revisar leitura (auto)'),
  ('K141', '算', 'Calcular', 'Vida Cotidiana', 15, 'そろ', 'SORO', '{"サン"}', '{"そろ"}', 14, true, 'Revisar leitura (auto)'),
  ('K142', '姉', 'Irmã mais velha', 'Vida Cotidiana', 15, 'あね', 'ANE', '{"シ"}', '{"あね","はは"}', 8, true, 'Revisar leitura (auto)'),
  ('K143', '市', 'Cidade; mercado', 'Vida Cotidiana', 15, 'いち', 'ICHI', '{"シ"}', '{"いち"}', 5, true, 'Revisar leitura (auto)'),
  ('K144', '思', 'Pensar; sentir', 'Vida Cotidiana', 15, 'おぼ', 'OBO', '{"シ"}', '{"おぼ.す","おも.う","おもえら.く"}', 9, true, 'Revisar leitura (auto)'),
  ('K145', '止', 'Parar', 'Vida Cotidiana', 15, 'と', 'TO', '{"シ"}', '{"-さ.し","-さ.す","-と.める","-ど.まり","-ど.め","-や.む","と.まる","と.める","とど.まる","とど.め","とど.める","や.む","や.める","よ.す"}', 4, true, 'Revisar leitura (auto)'),
  ('K146', '紙', 'Papel', 'Vida Cotidiana', 15, 'かみ', 'KAMI', '{"シ"}', '{"かみ"}', 10, true, 'Revisar leitura (auto)'),
  ('K147', '寺', 'Templo budista', 'Vida Cotidiana', 15, 'てら', 'TERA', '{"ジ"}', '{"てら"}', 6, true, 'Revisar leitura (auto)'),
  ('K148', '時', 'Tempo; hora', 'Vida Cotidiana', 15, 'とき', 'TOKI', '{"ジ"}', '{"-どき","とき"}', 10, true, 'Revisar leitura (auto)'),
  ('K149', '自', 'Si mesmo', 'Vida Cotidiana', 15, 'おの', 'ONO', '{"シ","ジ"}', '{"おの.ずから","おの.ずと","みずか.ら"}', 6, true, 'Revisar leitura (auto)'),
  ('K150', '室', 'Sala', 'Vida Cotidiana', 15, 'むろ', 'MURO', '{"シツ"}', '{"むろ"}', 9, true, 'Revisar leitura (auto)'),
  ('K151', '社', 'Empresa; santuário', 'Movimento e Ações', 16, 'やしろ', 'YASHIRO', '{"シャ"}', '{"やしろ"}', 7, true, 'Revisar leitura (auto)'),
  ('K152', '弱', 'Fraco', 'Movimento e Ações', 16, 'よわ', 'YOWA', '{"ジャク"}', '{"よわ.い","よわ.まる","よわ.める","よわ.る"}', 10, true, 'Revisar leitura (auto)'),
  ('K153', '首', 'Pescoço; cabeça', 'Movimento e Ações', 16, 'くび', 'KUBI', '{"シュ"}', '{"くび"}', 9, true, 'Revisar leitura (auto)'),
  ('K154', '秋', 'Outono', 'Movimento e Ações', 16, 'あき', 'AKI', '{"シュウ"}', '{"あき","とき"}', 9, true, 'Revisar leitura (auto)'),
  ('K155', '週', 'Semana', 'Movimento e Ações', 16, 'しゅう', 'SHUU', '{"シュウ"}', '{}', 11, true, 'Revisar leitura (auto)'),
  ('K156', '春', 'Primavera', 'Movimento e Ações', 16, 'はる', 'HARU', '{"シュン"}', '{"はる"}', 9, true, 'Revisar leitura (auto)'),
  ('K157', '書', 'Escrever; livro', 'Movimento e Ações', 16, 'か', 'KA', '{"ショ"}', '{"-が.き","-がき","か.く"}', 10, true, 'Revisar leitura (auto)'),
  ('K158', '少', 'Pouco', 'Movimento e Ações', 16, 'すく', 'SUKU', '{"ショウ"}', '{"すく.ない","すこ.し"}', 4, true, 'Revisar leitura (auto)'),
  ('K159', '場', 'Lugar', 'Movimento e Ações', 16, 'ば', 'BA', '{"ジョウ","チョウ"}', '{"ば"}', 12, true, 'Revisar leitura (auto)'),
  ('K160', '色', 'Cor', 'Movimento e Ações', 16, 'いろ', 'IRO', '{"シキ","ショク"}', '{"いろ"}', 6, true, 'Revisar leitura (auto)'),
  ('K161', '食', 'Comer; alimento', 'Movimento e Ações', 17, 'く', 'KU', '{"ショク","ジキ"}', '{"く.う","く.らう","た.べる","は.む"}', 9, true, 'Revisar leitura (auto)'),
  ('K162', '心', 'Coração; mente', 'Movimento e Ações', 17, 'こころ', 'KOKORO', '{"シン"}', '{"-ごころ","こころ"}', 4, true, 'Revisar leitura (auto)'),
  ('K163', '新', 'Novo', 'Movimento e Ações', 17, 'あたら', 'ATARA', '{"シン"}', '{"あたら.しい","あら-","あら.た","にい-"}', 13, true, 'Revisar leitura (auto)'),
  ('K164', '親', 'Pai/mãe; próximo', 'Movimento e Ações', 17, 'おや', 'OYA', '{"シン"}', '{"おや","おや-","した.しい","した.しむ"}', 16, true, 'Revisar leitura (auto)'),
  ('K165', '図', 'Mapa; desenho', 'Movimento e Ações', 17, 'え', 'E', '{"ズ","ト"}', '{"え","はか.る"}', 7, true, 'Revisar leitura (auto)'),
  ('K166', '数', 'Número; contar', 'Movimento e Ações', 17, 'かず', 'KAZU', '{"サク","シュ","ス","スウ","ソク"}', '{"かず","かぞ.える","しばしば","せ.める","わずらわ.しい"}', 13, true, 'Revisar leitura (auto)'),
  ('K167', '星', 'Estrela', 'Movimento e Ações', 17, 'ほし', 'HOSHI', '{"ショウ","セイ"}', '{"-ぼし","ほし"}', 9, true, 'Revisar leitura (auto)'),
  ('K168', '晴', 'Tempo aberto', 'Movimento e Ações', 17, 'は', 'HA', '{"セイ"}', '{"-ば.れ","は.らす","は.れ","は.れ-","は.れる"}', 12, true, 'Revisar leitura (auto)'),
  ('K169', '声', 'Voz', 'Movimento e Ações', 17, 'こえ', 'KOE', '{"ショウ","セイ"}', '{"こえ","こわ-"}', 7, true, 'Revisar leitura (auto)'),
  ('K170', '西', 'Oeste', 'Movimento e Ações', 17, 'にし', 'NISHI', '{"サイ","ス","セイ"}', '{"にし"}', 6, true, 'Revisar leitura (auto)'),
  ('K171', '切', 'Cortar', 'Movimento e Ações', 18, 'き', 'KI', '{"サイ","セツ"}', '{"-き.り","-き.る","-き.れ","-き.れる","-ぎ.り","-ぎ.れ","き.り","き.る","き.れ","き.れる"}', 4, true, 'Revisar leitura (auto)'),
  ('K172', '雪', 'Neve', 'Movimento e Ações', 18, 'ゆき', 'YUKI', '{"セツ"}', '{"ゆき"}', 11, true, 'Revisar leitura (auto)'),
  ('K173', '線', 'Linha', 'Movimento e Ações', 18, 'すじ', 'SUJI', '{"セン"}', '{"すじ"}', 15, true, 'Revisar leitura (auto)'),
  ('K174', '船', 'Navio; barco', 'Movimento e Ações', 18, 'ふね', 'FUNE', '{"セン"}', '{"ふな-","ふね"}', 11, true, 'Revisar leitura (auto)'),
  ('K175', '前', 'Antes; frente', 'Movimento e Ações', 18, 'まえ', 'MAE', '{"ゼン"}', '{"-まえ","まえ"}', 9, true, 'Revisar leitura (auto)'),
  ('K176', '組', 'Grupo; montar', 'Movimento e Ações', 18, 'く', 'KU', '{"ソ"}', '{"-ぐみ","く.む","くみ"}', 11, true, 'Revisar leitura (auto)'),
  ('K177', '走', 'Correr', 'Movimento e Ações', 18, 'はし', 'HASHI', '{"ソウ"}', '{"はし.る"}', 7, true, 'Revisar leitura (auto)'),
  ('K178', '多', 'Muitos', 'Movimento e Ações', 18, 'おお', 'OO', '{"タ"}', '{"おお.い","まさ.に","まさ.る"}', 6, true, 'Revisar leitura (auto)'),
  ('K179', '太', 'Grosso; grande', 'Movimento e Ações', 18, 'ふと', 'FUTO', '{"タ","タイ"}', '{"ふと.い","ふと.る"}', 4, true, 'Revisar leitura (auto)'),
  ('K180', '体', 'Corpo', 'Movimento e Ações', 18, 'かたち', 'KATACHI', '{"タイ","テイ"}', '{"かたち","からだ"}', 7, true, 'Revisar leitura (auto)'),
  ('K181', '台', 'Plataforma; base', 'Movimento e Ações', 19, 'うてな', 'UTENA', '{"タイ","ダイ"}', '{"うてな","つかさ","われ"}', 5, true, 'Revisar leitura (auto)'),
  ('K182', '谷', 'Vale', 'Movimento e Ações', 19, 'きわ', 'KIWA', '{"コク"}', '{"きわ.まる","たに"}', 7, true, 'Revisar leitura (auto)'),
  ('K183', '知', 'Saber', 'Movimento e Ações', 19, 'し', 'SHI', '{"チ"}', '{"し.らせる","し.る"}', 8, true, 'Revisar leitura (auto)'),
  ('K184', '地', 'Terra; área', 'Movimento e Ações', 19, 'じ', 'JI', '{"ジ","チ"}', '{}', 6, true, 'Revisar leitura (auto)'),
  ('K185', '池', 'Lagoa', 'Movimento e Ações', 19, 'いけ', 'IKE', '{"チ"}', '{"いけ"}', 6, true, 'Revisar leitura (auto)'),
  ('K186', '茶', 'Chá', 'Movimento e Ações', 19, 'さ', 'SA', '{"サ","チャ"}', '{}', 9, true, 'Revisar leitura (auto)'),
  ('K187', '昼', 'Dia; meio-dia', 'Movimento e Ações', 19, 'ひる', 'HIRU', '{"チュウ"}', '{"ひる"}', 9, true, 'Revisar leitura (auto)'),
  ('K188', '朝', 'Manhã', 'Movimento e Ações', 19, 'あさ', 'ASA', '{"チョウ"}', '{"あさ"}', 12, true, 'Revisar leitura (auto)'),
  ('K189', '長', 'Longo; chefe', 'Movimento e Ações', 19, 'おさ', 'OSA', '{"チョウ"}', '{"おさ","なが.い"}', 8, true, 'Revisar leitura (auto)'),
  ('K190', '鳥', 'Pássaro', 'Movimento e Ações', 19, 'とり', 'TORI', '{"チョウ"}', '{"とり"}', 11, true, 'Revisar leitura (auto)'),
  ('K191', '直', 'Direto; corrigir', 'Movimento e Ações', 20, 'す', 'SU', '{"ジカ","ジキ","チョク"}', '{"-なお.す","す.ぐ","ただ.ちに","なお.き","なお.す","なお.る"}', 8, true, 'Revisar leitura (auto)'),
  ('K192', '通', 'Passar; trânsito', 'Movimento e Ações', 20, 'かよ', 'KAYO', '{"ツ","ツウ"}', '{"-とお.り","-どお.し","-どお.り","かよ.う","とお.し","とお.す","とお.り","とお.る"}', 10, true, 'Revisar leitura (auto)'),
  ('K193', '弟', 'Irmão mais novo', 'Movimento e Ações', 20, 'おとうと', 'OTOUTO', '{"ダイ","テイ","デ"}', '{"おとうと"}', 7, true, 'Revisar leitura (auto)'),
  ('K194', '店', 'Loja', 'Movimento e Ações', 20, 'たな', 'TANA', '{"テン"}', '{"たな","みせ"}', 8, true, 'Revisar leitura (auto)'),
  ('K195', '点', 'Ponto', 'Movimento e Ações', 20, 'さ', 'SA', '{"テン"}', '{"さ.す","た.てる","つ.く","つ.ける","とぼ.す","とも.す","ぼち"}', 9, true, 'Revisar leitura (auto)'),
  ('K196', '電', 'Eletricidade', 'Movimento e Ações', 20, 'でん', 'DEN', '{"デン"}', '{}', 13, true, 'Revisar leitura (auto)'),
  ('K197', '冬', 'Inverno', 'Movimento e Ações', 20, 'ふゆ', 'FUYU', '{"トウ"}', '{"ふゆ"}', 5, true, 'Revisar leitura (auto)'),
  ('K198', '刀', 'Espada', 'Movimento e Ações', 20, 'かたな', 'KATANA', '{"トウ"}', '{"かたな","そり"}', 2, true, 'Revisar leitura (auto)'),
  ('K199', '東', 'Leste', 'Movimento e Ações', 20, 'ひがし', 'HIGASHI', '{"トウ"}', '{"ひがし"}', 8, true, 'Revisar leitura (auto)'),
  ('K200', '当', 'Acertar; correspondente', 'Movimento e Ações', 20, 'あ', 'A', '{"トウ"}', '{"あ.たり","あ.たる","あ.て","あ.てる","まさ.に","まさ.にべし"}', 6, true, 'Revisar leitura (auto)'),
  ('K201', '答', 'Resposta', 'Calendário e Sociedade', 21, 'こた', 'KOTA', '{"トウ"}', '{"こた.え","こた.える"}', 12, true, 'Revisar leitura (auto)'),
  ('K202', '頭', 'Cabeça', 'Calendário e Sociedade', 21, 'あたま', 'ATAMA', '{"ズ","ト","トウ"}', '{"-がしら","あたま","かしら","かぶり"}', 16, true, 'Revisar leitura (auto)'),
  ('K203', '同', 'Mesmo', 'Calendário e Sociedade', 21, 'おな', 'ONA', '{"ドウ"}', '{"おな.じ"}', 6, true, 'Revisar leitura (auto)'),
  ('K204', '道', 'Caminho', 'Calendário e Sociedade', 21, 'いう', 'IU', '{"トウ","ドウ"}', '{"いう","みち"}', 12, true, 'Revisar leitura (auto)'),
  ('K205', '読', 'Ler', 'Calendário e Sociedade', 21, 'よ', 'YO', '{"トウ","トク","ドク"}', '{"-よ.み","よ.む"}', 14, true, 'Revisar leitura (auto)'),
  ('K206', '内', 'Dentro', 'Calendário e Sociedade', 21, 'うち', 'UCHI', '{"ダイ","ナイ"}', '{"うち"}', 4, true, 'Revisar leitura (auto)'),
  ('K207', '南', 'Sul', 'Calendário e Sociedade', 21, 'みなみ', 'MINAMI', '{"ナ","ナン"}', '{"みなみ"}', 9, true, 'Revisar leitura (auto)'),
  ('K208', '肉', 'Carne', 'Calendário e Sociedade', 21, 'しし', 'SHISHI', '{"ニク"}', '{"しし"}', 6, true, 'Revisar leitura (auto)'),
  ('K209', '馬', 'Cavalo', 'Calendário e Sociedade', 21, 'うま', 'UMA', '{"バ"}', '{"うま","うま-","ま"}', 10, true, 'Revisar leitura (auto)'),
  ('K210', '買', 'Comprar', 'Calendário e Sociedade', 21, 'か', 'KA', '{"バイ"}', '{"か.う"}', 12, true, 'Revisar leitura (auto)'),
  ('K211', '売', 'Vender', 'Calendário e Sociedade', 22, 'う', 'U', '{"バイ"}', '{"う.る","う.れる"}', 7, true, 'Revisar leitura (auto)'),
  ('K212', '麦', 'Trigo; cevada', 'Calendário e Sociedade', 22, 'むぎ', 'MUGI', '{"バク"}', '{"むぎ"}', 7, true, 'Revisar leitura (auto)'),
  ('K213', '半', 'Metade', 'Calendário e Sociedade', 22, 'なか', 'NAKA', '{"ハン"}', '{"なか.ば"}', 5, true, 'Revisar leitura (auto)'),
  ('K214', '番', 'Número; turno', 'Calendário e Sociedade', 22, 'つが', 'TSUGA', '{"バン"}', '{"つが.い"}', 12, true, 'Revisar leitura (auto)'),
  ('K215', '父', 'Pai', 'Calendário e Sociedade', 22, 'ちち', 'CHICHI', '{"フ"}', '{"ちち"}', 4, true, 'Revisar leitura (auto)'),
  ('K216', '風', 'Vento', 'Calendário e Sociedade', 22, 'かぜ', 'KAZE', '{"フ","フウ"}', '{"かざ-","かぜ"}', 9, true, 'Revisar leitura (auto)'),
  ('K217', '聞', 'Ouvir; perguntar', 'Calendário e Sociedade', 22, 'き', 'KI', '{"ブン","モン"}', '{"き.く","き.こえる"}', 14, true, 'Revisar leitura (auto)'),
  ('K218', '米', 'Arroz', 'Calendário e Sociedade', 22, 'こめ', 'KOME', '{"ベイ","マイ","メエトル"}', '{"こめ","よね"}', 6, true, 'Revisar leitura (auto)'),
  ('K219', '歩', 'Andar', 'Calendário e Sociedade', 22, 'あゆ', 'AYU', '{"フ","ブ","ホ"}', '{"あゆ.む","ある.く"}', 8, true, 'Revisar leitura (auto)'),
  ('K220', '母', 'Mãe', 'Calendário e Sociedade', 22, 'はは', 'HAHA', '{"ボ"}', '{"はは","も"}', 5, true, 'Revisar leitura (auto)'),
  ('K221', '方', 'Direção; pessoa', 'Calendário e Sociedade', 23, 'かた', 'KATA', '{"ホウ"}', '{"-かた","-がた","かた"}', 4, true, 'Revisar leitura (auto)'),
  ('K222', '北', 'Norte', 'Calendário e Sociedade', 23, 'きた', 'KITA', '{"ホク"}', '{"きた"}', 5, true, 'Revisar leitura (auto)'),
  ('K223', '妹', 'Irmã mais nova', 'Calendário e Sociedade', 23, 'いもうと', 'IMOUTO', '{"マイ"}', '{"いもうと"}', 8, true, 'Revisar leitura (auto)'),
  ('K224', '毎', 'Cada', 'Calendário e Sociedade', 23, 'ごと', 'GOTO', '{"マイ"}', '{"-ごと.に","ごと"}', 6, true, 'Revisar leitura (auto)'),
  ('K225', '万', 'Dez mil', 'Calendário e Sociedade', 23, 'よろず', 'YOROZU', '{"バン","マン"}', '{"よろず"}', 3, true, 'Revisar leitura (auto)'),
  ('K226', '明', 'Claro; brilhante', 'Calendário e Sociedade', 23, 'あ', 'A', '{"ミョウ","ミン","メイ"}', '{"-あ.け","あ.かす","あ.かり","あ.く","あ.くる","あ.ける","あか.らむ","あか.るい","あか.るむ","あき.らか"}', 8, true, 'Revisar leitura (auto)'),
  ('K227', '鳴', 'Soar; cantar', 'Calendário e Sociedade', 23, 'な', 'NA', '{"メイ"}', '{"な.く","な.らす","な.る"}', 14, true, 'Revisar leitura (auto)'),
  ('K228', '毛', 'Pelo', 'Calendário e Sociedade', 23, 'け', 'KE', '{"モウ"}', '{"け"}', 4, true, 'Revisar leitura (auto)'),
  ('K229', '門', 'Portão', 'Calendário e Sociedade', 23, 'かど', 'KADO', '{"モン"}', '{"かど","と"}', 8, true, 'Revisar leitura (auto)'),
  ('K230', '夜', 'Noite', 'Calendário e Sociedade', 23, 'よ', 'YO', '{"ヤ"}', '{"よ","よる"}', 8, true, 'Revisar leitura (auto)'),
  ('K231', '野', 'Campo', 'Calendário e Sociedade', 24, 'の', 'NO', '{"ショ","ヤ"}', '{"の","の-"}', 11, true, 'Revisar leitura (auto)'),
  ('K232', '矢', 'Flecha', 'Calendário e Sociedade', 24, 'や', 'YA', '{"シ"}', '{"や"}', 5, true, 'Revisar leitura (auto)'),
  ('K233', '友', 'Amigo', 'Calendário e Sociedade', 24, 'とも', 'TOMO', '{"ユウ"}', '{"とも"}', 4, true, 'Revisar leitura (auto)'),
  ('K234', '曜', 'Dia da semana', 'Calendário e Sociedade', 24, 'よう', 'YOU', '{"ヨウ"}', '{}', 18, true, 'Revisar leitura (auto)'),
  ('K235', '用', 'Usar', 'Calendário e Sociedade', 24, 'もち', 'MOCHI', '{"ヨウ"}', '{"もち.いる"}', 5, true, 'Revisar leitura (auto)'),
  ('K236', '来', 'Vir', 'Calendário e Sociedade', 24, 'き', 'KI', '{"タイ","ライ"}', '{"き","き.たす","き.たる","きた.す","きた.る","く.る","こ"}', 7, true, 'Revisar leitura (auto)'),
  ('K237', '理', 'Razão; lógica', 'Calendário e Sociedade', 24, 'ことわり', 'KOTOWARI', '{"リ"}', '{"ことわり"}', 11, true, 'Revisar leitura (auto)'),
  ('K238', '話', 'Falar; história', 'Calendário e Sociedade', 24, 'はな', 'HANA', '{"ワ"}', '{"はな.す","はなし"}', 13, true, 'Revisar leitura (auto)'),
  ('K239', '悪', 'Ruim; mal', 'Calendário e Sociedade', 24, 'あ', 'A', '{"アク","オ"}', '{"-にく.い","あ.し","ああ","いずくに","いずくんぞ","にく.い","にく.む","わる-","わる.い"}', 11, true, 'Revisar leitura (auto)'),
  ('K240', '安', 'Barato; tranquilo', 'Calendário e Sociedade', 24, 'やす', 'YASU', '{"アン"}', '{"やす","やす.い","やす.まる","やす.らか"}', 6, true, 'Revisar leitura (auto)'),
  ('K241', '暗', 'Escuro', 'Calendário e Sociedade', 25, 'くら', 'KURA', '{"アン"}', '{"くら.い","くら.む","くれ.る"}', 13, true, 'Revisar leitura (auto)'),
  ('K242', '委', 'Confiar; comissão', 'Calendário e Sociedade', 25, 'ゆだ', 'YUDA', '{"イ"}', '{"ゆだ.ねる"}', 8, true, 'Revisar leitura (auto)'),
  ('K243', '意', 'Ideia; intenção', 'Calendário e Sociedade', 25, 'い', 'I', '{"イ"}', '{}', 13, true, 'Revisar leitura (auto)'),
  ('K244', '医', 'Medicina; médico', 'Calendário e Sociedade', 25, 'い', 'I', '{"イ"}', '{"い.する","い.やす","くすし"}', 7, true, 'Revisar leitura (auto)'),
  ('K245', '育', 'Criar; educar', 'Calendário e Sociedade', 25, 'そだ', 'SODA', '{"イク"}', '{"そだ.ち","そだ.つ","そだ.てる","はぐく.む"}', 8, true, 'Revisar leitura (auto)'),
  ('K246', '員', 'Membro; funcionário', 'Calendário e Sociedade', 25, 'いん', 'IN', '{"イン"}', '{}', 10, true, 'Revisar leitura (auto)'),
  ('K247', '飲', 'Beber', 'Calendário e Sociedade', 25, 'の', 'NO', '{"イン","オン"}', '{"-の.み","の.む"}', 12, true, 'Revisar leitura (auto)'),
  ('K248', '院', 'Instituição', 'Calendário e Sociedade', 25, 'いん', 'IN', '{"イン"}', '{}', 10, true, 'Revisar leitura (auto)'),
  ('K249', '運', 'Transportar; sorte', 'Calendário e Sociedade', 25, 'はこ', 'HAKO', '{"ウン"}', '{"はこ.ぶ"}', 12, true, 'Revisar leitura (auto)'),
  ('K250', '泳', 'Nadar', 'Calendário e Sociedade', 25, 'およ', 'OYO', '{"エイ"}', '{"およ.ぐ"}', 8, true, 'Revisar leitura (auto)'),
  ('K251', '駅', 'Estação', 'Consolidação', 26, 'えき', 'EKI', '{"エキ"}', '{}', 14, true, 'Revisar leitura (auto)'),
  ('K252', '央', 'Centro', 'Consolidação', 26, 'おう', 'OU', '{"オウ"}', '{}', 5, true, 'Revisar leitura (auto)'),
  ('K253', '横', 'Lado; horizontal', 'Consolidação', 26, 'よこ', 'YOKO', '{"オウ"}', '{"よこ"}', 15, true, 'Revisar leitura (auto)'),
  ('K254', '屋', 'Casa; loja', 'Consolidação', 26, 'や', 'YA', '{"オク"}', '{"や"}', 9, true, 'Revisar leitura (auto)'),
  ('K255', '温', 'Morno; temperatura', 'Consolidação', 26, 'あたた', 'ATATA', '{"オン"}', '{"あたた.か","あたた.かい","あたた.まる","あたた.める","ぬく"}', 12, true, 'Revisar leitura (auto)'),
  ('K256', '化', 'Transformar', 'Consolidação', 26, 'け', 'KE', '{"カ","ケ"}', '{"け.する","ば.かす","ば.ける","ふ.ける"}', 4, true, 'Revisar leitura (auto)'),
  ('K257', '荷', 'Carga; bagagem', 'Consolidação', 26, 'に', 'NI', '{"カ"}', '{"に"}', 10, true, 'Revisar leitura (auto)'),
  ('K258', '界', 'Mundo; limite', 'Consolidação', 26, 'かい', 'KAI', '{"カイ"}', '{}', 9, true, 'Revisar leitura (auto)'),
  ('K259', '開', 'Abrir', 'Consolidação', 26, 'あ', 'A', '{"カイ"}', '{"-びら.き","あ.く","あ.ける","ひら.き","ひら.く","ひら.ける"}', 12, true, 'Revisar leitura (auto)'),
  ('K260', '階', 'Andar; escada', 'Consolidação', 26, 'きざはし', 'KIZAHASHI', '{"カイ"}', '{"きざはし"}', 12, true, 'Revisar leitura (auto)'),
  ('K261', '寒', 'Frio', 'Consolidação', 27, 'さむ', 'SAMU', '{"カン"}', '{"さむ.い"}', 12, true, 'Revisar leitura (auto)'),
  ('K262', '感', 'Sentimento', 'Consolidação', 27, 'かん', 'KAN', '{"カン"}', '{}', 13, true, 'Revisar leitura (auto)'),
  ('K263', '漢', 'China; chinês', 'Consolidação', 27, 'かん', 'KAN', '{"カン"}', '{}', 13, true, 'Revisar leitura (auto)'),
  ('K264', '館', 'Edifício; salão', 'Consolidação', 27, 'たて', 'TATE', '{"カン"}', '{"たて","やかた"}', 16, true, 'Revisar leitura (auto)'),
  ('K265', '岸', 'Margem; costa', 'Consolidação', 27, 'きし', 'KISHI', '{"ガン"}', '{"きし"}', 8, true, 'Revisar leitura (auto)'),
  ('K266', '期', 'Período', 'Consolidação', 27, 'き', 'KI', '{"キ","ゴ"}', '{}', 12, true, 'Revisar leitura (auto)'),
  ('K267', '起', 'Levantar; começar', 'Consolidação', 27, 'お', 'O', '{"キ"}', '{"お.きる","お.こす","お.こる","おこ.す","た.つ"}', 10, true, 'Revisar leitura (auto)'),
  ('K268', '客', 'Visitante; cliente', 'Consolidação', 27, 'かく', 'KAKU', '{"カク","キャク"}', '{}', 9, true, 'Revisar leitura (auto)'),
  ('K269', '宮', 'Palácio; santuário', 'Consolidação', 27, 'みや', 'MIYA', '{"キュウ","ク","クウ","グウ"}', '{"みや"}', 10, true, 'Revisar leitura (auto)'),
  ('K270', '急', 'Urgente; apressar', 'Consolidação', 27, 'いそ', 'ISO', '{"キュウ"}', '{"いそ.ぎ","いそ.ぐ","せ.く"}', 9, true, 'Revisar leitura (auto)'),
  ('K271', '球', 'Bola; esfera', 'Consolidação', 28, 'たま', 'TAMA', '{"キュウ"}', '{"たま"}', 11, true, 'Revisar leitura (auto)'),
  ('K272', '究', 'Pesquisar', 'Consolidação', 28, 'きわ', 'KIWA', '{"キュウ","ク"}', '{"きわ.める"}', 7, true, 'Revisar leitura (auto)'),
  ('K273', '級', 'Classe; nível', 'Consolidação', 28, 'きゅう', 'KYUU', '{"キュウ"}', '{}', 9, true, 'Revisar leitura (auto)'),
  ('K274', '去', 'Passado; ir embora', 'Consolidação', 28, 'さ', 'SA', '{"キョ","コ"}', '{"-さ.る","さ.る"}', 5, true, 'Revisar leitura (auto)'),
  ('K275', '橋', 'Ponte', 'Consolidação', 28, 'はし', 'HASHI', '{"キョウ"}', '{"はし"}', 16, true, 'Revisar leitura (auto)'),
  ('K276', '業', 'Trabalho; indústria', 'Consolidação', 28, 'わざ', 'WAZA', '{"ギョウ","ゴウ"}', '{"わざ"}', 13, true, 'Revisar leitura (auto)'),
  ('K277', '局', 'Departamento; estação', 'Consolidação', 28, 'つぼね', 'TSUBONE', '{"キョク"}', '{"つぼね"}', 7, true, 'Revisar leitura (auto)'),
  ('K278', '曲', 'Curva; música', 'Consolidação', 28, 'くま', 'KUMA', '{"キョク"}', '{"くま","ま.がる","ま.げる"}', 6, true, 'Revisar leitura (auto)'),
  ('K279', '銀', 'Prata', 'Consolidação', 28, 'しろがね', 'SHIROGANE', '{"ギン"}', '{"しろがね"}', 14, true, 'Revisar leitura (auto)'),
  ('K280', '区', 'Distrito', 'Consolidação', 28, 'おう', 'OU', '{"オウ","ク","コウ"}', '{}', 4, true, 'Revisar leitura (auto)'),
  ('K281', '苦', 'Sofrimento; difícil', 'Consolidação', 29, 'くる', 'KURU', '{"ク"}', '{"-ぐる.しい","くる.しい","くる.しむ","くる.しめる","にが.い","にが.る"}', 8, true, 'Revisar leitura (auto)'),
  ('K282', '具', 'Ferramenta', 'Consolidação', 29, 'そな', 'SONA', '{"グ"}', '{"そな.える","つぶさ.に"}', 8, true, 'Revisar leitura (auto)'),
  ('K283', '君', 'Você; senhor', 'Consolidação', 29, 'きみ', 'KIMI', '{"クン"}', '{"-ぎみ","きみ"}', 7, true, 'Revisar leitura (auto)'),
  ('K284', '係', 'Responsável; relação', 'Consolidação', 29, 'かか', 'KAKA', '{"ケイ"}', '{"-がかり","かか.る","かか.わる","かかり"}', 9, true, 'Revisar leitura (auto)'),
  ('K285', '軽', 'Leve', 'Consolidação', 29, 'かる', 'KARU', '{"キョウ","キン","ケイ"}', '{"かる.い","かろ.やか","かろ.んじる"}', 12, true, 'Revisar leitura (auto)'),
  ('K286', '決', 'Decidir', 'Consolidação', 29, 'き', 'KI', '{"ケツ"}', '{"-ぎ.め","き.まる","き.める","さ.く"}', 7, true, 'Revisar leitura (auto)'),
  ('K287', '血', 'Sangue', 'Consolidação', 29, 'ち', 'CHI', '{"ケツ"}', '{"ち"}', 6, true, 'Revisar leitura (auto)'),
  ('K288', '研', 'Estudar; polir', 'Consolidação', 29, 'と', 'TO', '{"ケン"}', '{"と.ぐ"}', 9, true, 'Revisar leitura (auto)'),
  ('K289', '県', 'Prefeitura', 'Consolidação', 29, 'か', 'KA', '{"ケン"}', '{"か.ける"}', 9, true, 'Revisar leitura (auto)'),
  ('K290', '庫', 'Depósito', 'Consolidação', 29, 'くら', 'KURA', '{"ク","コ"}', '{"くら"}', 10, true, 'Revisar leitura (auto)'),
  ('K291', '湖', 'Lago', 'Consolidação', 30, 'みずうみ', 'MIZUUMI', '{"コ"}', '{"みずうみ"}', 12, true, 'Revisar leitura (auto)'),
  ('K292', '向', 'Direção; voltar-se', 'Consolidação', 30, 'む', 'MU', '{"コウ"}', '{"-む.き","-む.け","む.い","む.かい","む.かう","む.く","む.ける","む.こう","む.こう-","むか.い","むこ"}', 6, true, 'Revisar leitura (auto)'),
  ('K293', '幸', 'Felicidade', 'Consolidação', 30, 'さいわ', 'SAIWA', '{"コウ"}', '{"さいわ.い","さち","しあわ.せ"}', 8, true, 'Revisar leitura (auto)'),
  ('K294', '港', 'Porto', 'Consolidação', 30, 'みなと', 'MINATO', '{"コウ"}', '{"みなと"}', 12, true, 'Revisar leitura (auto)'),
  ('K295', '号', 'Número; título', 'Consolidação', 30, 'さけ', 'SAKE', '{"ゴウ"}', '{"さけ.ぶ","よびな"}', 5, true, 'Revisar leitura (auto)'),
  ('K296', '根', 'Raiz', 'Consolidação', 30, 'ね', 'NE', '{"コン"}', '{"-ね","ね"}', 10, true, 'Revisar leitura (auto)'),
  ('K297', '祭', 'Festival', 'Consolidação', 30, 'まつ', 'MATSU', '{"サイ"}', '{"まつ.り","まつ.る","まつり"}', 11, true, 'Revisar leitura (auto)'),
  ('K298', '坂', 'Ladeira', 'Consolidação', 30, 'さか', 'SAKA', '{"ハン"}', '{"さか"}', 7, true, 'Revisar leitura (auto)'),
  ('K299', '皿', 'Prato', 'Consolidação', 30, 'さら', 'SARA', '{"ベイ"}', '{"さら"}', 5, true, 'Revisar leitura (auto)'),
  ('K300', '仕', 'Servir; trabalhar', 'Consolidação', 30, 'つか', 'TSUKA', '{"シ","ジ"}', '{"つか.える"}', 5, true, 'Revisar leitura (auto)')
on conflict (id) do update set
  kanji=excluded.kanji, significado=excluded.significado, mundo=excluded.mundo,
  fase=excluded.fase, hiragana=excluded.hiragana, romaji=excluded.romaji,
  onyomi=excluded.onyomi, kunyomi=excluded.kunyomi, tracos=excluded.tracos,
  needs_review=excluded.needs_review, status=excluded.status;
